# -*- coding: utf-8 -*-
"""Explore Survey Free Responses

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yKzQX-ziur-IfWN8svH7WE1ewWR-4N9M
"""

from collections import Counter
from string import punctuation

import pandas as pd

from nltk.corpus import stopwords
from nltk import word_tokenize
#nltk.download('stopwords')
#nltk.download('punkt')
#print(stopwords.words('english'))

english_stopwords = stopwords.words('english')

responses = {}

def ngrams(text, n=2):
    return zip(*[text[i:] for i in range(n)])

def remove_stopwords_from_string(text):
    return ' '.join([word for word in word_tokenize(text) if word not in english_stopwords and len(word) > 2])

def ngrams_summary_of_question(current_question='Q1', ngram_max=2, results_n=15):
    current_question_cleaned = current_question + '_clean'
    df[current_question_cleaned] = df[current_question].str.lower().apply(lambda text: remove_stopwords_from_string(text))

    responses[current_question] = df[current_question_cleaned].str.lower()
    ngram_counts = Counter(ngrams(word_tokenize('\n'.join(responses[current_question])), ngram_max))
    return ngram_counts.most_common()[:results_n]

df = pd.read_csv('example.csv', header=0, names=['Q1', 'Q2', 'Q3', 'Q4'])
df.head()

for q in ['Q1', 'Q2', 'Q3', 'Q4']:
    print('Top ngrams for {}'.format(q))
    count = 0
    for result in ngrams_summary_of_question(q, 1, 25):
        if count == 3:
            print()
            count = 0
        print(result, sep='', end='')
        count += 1
    print()
    print()